---
shorten: 
  I'm: I am
  You're: You are
  you're: you are
  She's: She is
  she's: she is
  He's: He is
  he's: he is,
  We're: We are
  we're: we are
  They're: They are
  they're: they are
  It's: It is
  it's: it is
  That's: That is
  that's: that is
  There's: There is
  there's: there is
  These're: These are
  these're: these are
  Those're: Those are
  those're: those are
  How's: How is
  how's: how is
  How're: How are
  how're: how are
  What's: What is
  what's: what is
  What're: What are
  what're: what are
  Who's: Who is
  who's: who is
  Who're: Who are
  who're: who are
  When's: When is
  when's: when is
  When're: When are
  when're: when are
  Where's: Where is
  where's: where is
  Where're: Where are
  where're: where are
  Why's: Why is
  why's: why is
  Why're: Why are
  why're: why are
  Isn't: Is not
  isn't: is not
  Aren't: Are not
  aren't: are not
  Wasn't: Was not
  wasn't: was not
  Weren't: Were not
  weren't: were not
  Don't: Do not
  don't: do not
  Doesn't: Does not
  doesn't: does not
  Didn't: Did not
  didn't: did not
  Haven't: Have not
  haven't: have not
  Hasn't: Has not
  hasn't: has not
  Can't: Can not
  can't: can not
  Cannot: Can not
  cannot: can not
  Couldn't: Could not
  couldn't: could not
  Mustn't: Must not
  mustn't: must not
  Won't: Will not
  won't: will not
  Wouldn't: Would not
  wouldn't: would not
  Shouldn't: Should not
  shouldn't: should not
  Shan't: Shall not
  shan't: shall not
  I've: I have
  You've: You have
  you've: you have
  #She's: She has
  #she's: she has
  #He's: He has
  #he's: he has
  We've: We have
  we've: we have
  They've: They have
  they've: they have
  It's: It has
  Could've: Could have
  could've: could have
  Would've: Would have
  would've: would have
  I'll: I will
  You'll: You will
  you'll: you will
  He'll: He will
  he'll: he will
  She'll: She will
  she'll: she will
  We'll: We will
  we'll: we will
  They'll: They will
  they'll: they will
  This'll: This will
  this'll: this will
  That'll: That will
  that'll: that will
  These'll: These will
  these'll: these will
  Those'll: Those will
  those'll: those will
  It'll: It will
  it'll: it will
  How'll: How will
